config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #delete "produtos/:id", to: "produtos#destroy", as: :produto
  #post "produtos", to: "produtos#create"
  #get "produtos/new", to: "produtos#new"
  get "produtos/search", to: "produtos#search", as: :search_produto
  resources :produtos , only: [:new, :create, :destroy, :edit, :update]
  root to: "produtos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord

    belongs_to :departamento, optional: true

    validates :preco, :quantidade, :departamento, presence: true
    validates :nome, length: { minimum: 4}
    validates :descricao, length: { minimum: 5, maximum:200}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
    @id = params[:id]
    @produtos_por_departamento = Produto.where "departamento_id = ?", "#{@id}"
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to departamentos_url, notice: 'Departamento was successfully created.' }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController


    before_action :set_produto, only: [:edit, :update, :destroy]
    before_action :carrega_departamento, only: [:new, :create, :update]

    def index
        @produtos = Produto.order(nome: :asc).limit 5
        @produtos_com_desconto = Produto.order(:preco).limit 1
    end

    def new
        @produto = Produto.new
    end 
    
    def edit
        renderiza_departamento :edit
    end

    def update        
        if @produto.update get_produto_params
            display_message("alterado")
        else
            renderiza_departamento :edit
        end
    end

    def create        
        @produto = Produto.new get_produto_params
        if @produto.save
            display_message("criado")
        else
            renderiza_departamento :new
        end
    end

    def destroy
        @produto.destroy
        redirect_to root_url
    end

    def search
        @nome = params[:nome]
        @produtos = Produto.where "nome like ?", "%#{@nome}%"
    end

    def carrega_departamento
        @departamentos = Departamento.all
    end

    def display_message(acao)
        flash[:notice] = "Produto #{acao} com sucesso!"
        redirect_to root_url
    end

    private

    def get_produto_params
        params.require(:produto).permit(:nome, :descricao, :preco,
        :quantidade, :departamento_id)
    end

    def set_produto
        @produto = Produto.find(params[:id])
    end

    def renderiza_departamento(view)
        carrega_departamento
        render view
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento, local: true) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Ver Produtos', @departamento, class: "btn btn-default" %> |
<%= link_to 'Voltar', departamentos_path, class: "btn btn-default" %>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>

<table class="table table-bordered table-hoover">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Ver Produtos', departamento, class: "btn btn-default" %></td>
        <td><%= link_to 'Editar departamento', edit_departamento_path(departamento), class: "btn btn-default" %></td>
        <td><%= link_to 'Deletar', departamento, method: :delete, class: "btn btn-danger", data: { confirm: "Você deseja remover o departamento #{departamento.nome}?" } %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Departamento', new_departamento_path, class: "btn btn-default" %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Voltar', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered table-hoover">
    <thead>
        <%= render  "produtos/coluna" %>
    </thead>
    <tbody>
        <%= render @produtos_por_departamento %>
    </tbody>
</table>

<%= link_to 'Editar Departamento', edit_departamento_path(@departamento), class: "btn btn-default" %> |
<%= link_to 'Voltar', departamentos_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= nav_bar brand: "PPLoja", brand_link: root_url do %>
        <%= menu_group do %>
          <%= menu_item "Inserir Produto", new_produto_path	%>
          <%= menu_item "Departamentos", departamentos_path	%>
        <% end %>
        <%= form_tag search_produto_path, method: :get, class:"navbar-form navbar-right" do %>
          <div class="form-group">
            <%= text_field_tag :nome, @nome, class:"form-control"  %>
            <%= button_to  "Buscar", nil, class:"btn btn-default btn-rounded btn-sm my-0" %>
          </div>
        <% end %>
      <% end %>
        <div class="container">
          <%= yield %>
        </div>
  </body>
</html>

app/views/produtos/_coluna.html.erb
<tr>
    <td>Nome</td>
    <td>Descrição</td>
    <td>Departamento</td>
    <td>Preço</td>
    <td>Quantidade</td>
    <td colspan="2"></td>
</tr>

app/views/produtos/_form.html.erb
<% @produto.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
        <%= msg %>
    </div>   
<% end %>

<%= form_for @produto do |form| %>
    <div class="row">
        <div class="col-sm-3">
            <div class="form-group">
                <%= form.label :nome %>
                <%= form.text_field :nome, class:"form-control" %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <div class="form-group">
                <%= form.label :descricao %>
                <%= form.text_area :descricao, class:"form-control", rows:"4" %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :departamento %>
                <%= form.collection_select :departamento_id, @departamentos, :id, :nome, {}, class:"form-control" %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :preco %>
                <%= form.number_field :preco, class:"form-control", step:"0.5" %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <%= form.label :quantidade %>
                <%= form.number_field :quantidade, class:"form-control" %>
            </div>
        </div>
    </div>

    <%= form.submit texto_da_acao ,class:"btn btn-success" %>
<% end %>

app/views/produtos/_produto.html.erb
<tr>
    <td><%= produto.nome %></td>
    <td><%= produto.descricao %></td>
    <td><%= produto.departamento.nome %></td>
    <td><%= produto.preco %></td>
    <td><%= produto.quantidade %></td>
    <td><%= link_to "Editar", edit_produto_path(produto), class: "btn btn-default" %></td>
    <td><%= button_to "Remover", produto, method: :delete, class: "btn btn-danger", data: {confirm: "Você deseja remover o produto #{produto.nome}?"} %></td>
</tr>

app/views/produtos/edit.html.erb
<%= render  partial: "form", locals: {texto_da_acao: "Editar"}%>

app/views/produtos/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success", role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>
<table class="table table-bordered table-hoover">
    <thead>
        <%= render  "coluna" %>
    </thead>
    <tbody>
        <%= render @produtos %>
    </tbody>
</table>
<div class="alert alert-success" role="alert">
    <h4 class="alert heading">Produtos com desconto</h4>
</div>
<table class="table table-bordered table-hoover">
    <thead>
        <%= render  "coluna" %>
    </thead>
    <tbody>
        <%= render @produtos_com_desconto %>
    </tbody>
</table>

app/views/produtos/new.html.erb
<%= render  partial: "form", locals: {texto_da_acao: "Criar"}%>

app/views/produtos/search.html.erb
<table class="table table-bordered table-hoover">
    <thead>
       <%= render  "coluna" %>
    </thead>
    <tbody>
        <%= render @produtos %>
    </tbody>
</table>